AWSTemplateFormatVersion: '2010-09-09'
Description: Management Account Resources

Resources:
  MainSQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MainRequestQueue

  ResultsDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ResultsTable
      AttributeDefinitions:
        - AttributeName: RequestId
          AttributeType: S
      KeySchema:
        - AttributeName: RequestId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5