AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Organization-wide StackSet to create and deploy resources and Lambda function using SAM

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: MyBatchRequestLambda
      Handler: lambda.lambda_handler  # Update with your actual handler function
      Runtime: python3.9
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref SNSTopic
          ECR_PUBLIC_REPO_ARN: !Sub arn:aws:ecr-public::${AWS::AccountId}:repository/my-ecr-public-repo
          ECR_PRIVATE_REPO_ARN: !Sub arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/my-ecr-private-repo
          IAM_ROLE_ARN: !GetAtt IAMRole.Arn
          DYNAMODB_TABLE: MyResultsTable
          SQS_QUEUE_URL: !Ref SQSQueue
      Policies:
        - DynamoDBCrudPolicy:
            TableName: MyResultsTable
        - SQSSendMessagePolicy:
            QueueName: MyRequestQueue
        - SNSPublishPolicy:
            TopicName: MySNSTopic
        - ECRPublicPolicy:
            RepositoryName: my-ecr-public-repo
        - ECRPrivatePolicy:
            RepositoryName: my-ecr-private-repo
        - IAMPolicy:
            IAMRoleName: MyLambdaExecutionRole

  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: MyLambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DynamoDBCrudPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:GetItem
                Resource: '*'
        - PolicyName: SQSSendMessagePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource: !GetAtt SQSQueue.Arn
        - PolicyName: SNSPublishPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Ref SNSTopic
        - PolicyName: ECRPublicPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr-public:InitiateLayerUpload
                Resource: !Sub arn:aws:ecr-public::${AWS::AccountId}:repository/my-ecr-public-repo
        - PolicyName: ECRPrivatePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:InitiateLayerUpload
                Resource: !Sub arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/my-ecr-private-repo
        - PolicyName: IAMPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - iam:UpdateAssumeRolePolicy
                Resource: !GetAtt IAMRole.Arn

  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: MySNSTopic

  ECRPublicRepository:
    Type: AWS::ECR::PublicRepository
    Properties:
      RepositoryName: my-ecr-public-repo

  ECRPrivateRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: my-ecr-private-repo

  SQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MyRequestQueue

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MyResultsTable
      AttributeDefinitions:
        - AttributeName: ResourceId
          AttributeType: S
      KeySchema:
        - AttributeName: ResourceId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
