name: continuous-integration

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: make setup-dev

      - name: Run bandit (security test)
        run: make security-test

      - name: Run pytest (unit tests)
        run: make test

      - name: Install the package to make sure nothing is randomly broken
        run: make install

