name: Deploy Quiet Riot Dev
run-name: Deploy commit ${{ github.sha }} by @${{ github.actor }}

on:
  push:
    branches:
      - 'dev'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::201012399609:role/github-actions-role
          role-session-name: quiet-riot-commit-${{ github.sha }}
          
      - name: Install AWS CLI
        run: sudo apt-get install -y awscli

      - name: Zip Lambda Functions
        working-directory: infra/child_accounts
        run: zip -r lambda_code.zip lambda_function

      - name: Upload Lambda Code to S3
        run: aws s3 cp infra/child_accounts/lambda_code.zip s3://quiet-riot-global-bucket/lambda_code.zip

      - name: Package Management Account CloudFormation Template
        working-directory: infra/org_mgmt_account
        run: |
          aws cloudformation package \
            --template-file aws_cfn_infrastructure.yaml \
            --s3-bucket quiet-riot-global-bucket \
            --output-template-file packaged-template-mgmt.yaml \
            --region us-east-1

      - name: Deploy Management Account CloudFormation Stack
        working-directory: infra/org_mgmt_account
        run: |
          aws cloudformation deploy \
            --template-file packaged-template-mgmt.yaml \
            --stack-name QuietRiotMgmt \
            --capabilities CAPABILITY_NAMED_IAM \
            --region us-east-1

      - name: Package Child Account CloudFormation Template
        working-directory: infra/child_accounts
        run: |
          aws cloudformation package \
            --template-file aws_cfn_infrastructure.yaml \
            --s3-bucket quiet-riot-global-bucket \
            --output-template-file packaged-template-child.yaml \
            --region us-east-1

      - name: Deploy Child Account CloudFormation StackSet
        working-directory: infra/child_accounts
        run: |
          aws cloudformation create-stack-set \
            --stack-set-name QuietRiotChildAccounts \
            --template-body file://packaged-template-child.yaml \
            --capabilities CAPABILITY_NAMED_IAM \
            --region us-east-1

      - name: Get CloudFormation Stack Output Information
        run: aws cloudformation describe-stacks --stack-name QuietRiotMgmt --query "Stacks[0].Outputs" --output text
